language: node_js
node_js:
  - "9"
install:
  - travis_wait ./install.sh
cache:
  directories:
    - "src/server/node_modules"
    - "src/client/node_modules"
script:
  - npm test
  - npm run coverage
