language: node_js
node_js:
  - "node"
install:
  - travis_wait ./install.sh
cache:
  directories:
    - "src/server/node_modules"
    - "src/client/node_modules"
script:
  - npm test --prefix src/server
  - npm test --prefix src/client
  - npm run coverage --prefix src/server
  - npm run coverage --prefix src/client
