language: node_js
node_js:
  - "node"
install:
  - ./install.sh
cache:
  directories:
    - "src/server/node_modules"
script:
  - ls -a . src src/server src/server/tests
  - npm test --prefix src/server
