language: node_js
node_js:
  - "node"
install:
  - ./install.sh
cache:
  directories:
    - "src/server/node_modules"
script:
  - npm test --prefix src/server
after_success:
  - npm run coverage --prefix src/server
